FROM holochain/holochain-rust:develop

RUN apt-get update && apt-get install --yes \
  git \
  qtdeclarative5-dev \
  nodejs \
  npm

USER holochain

RUN rustup default nightly
RUN rustup target add wasm32-unknown-unknown
WORKDIR /holochain

ENV PATH "/holochain/holochain-cmd/target/release:/holochain/holosqape/holoconsole:$PATH"

WORKDIR /holochain