#!/bin/bash

if [ -n "$HOST_UID" ]; then
  OLDID=`id -u root`
  if [ "$OLDID" != "$HOST_UID" ]; then
    usermod -u "$HOST_UID" root
    groupmod -g "$HOST_UID" root
    usermod -g "$HOST_UID" root
    chown -R -h "$HOST_UID":"$HOST_UID" /home/holochain
  fi
fi

gosu root "$@"
