#!/bin/bash
#rustup toolchain install nightly-x86_64-unknown-linux-gnu
#rustup toolchain install nightly-2018-07-17-x86_64-unknown-linux-gnu
#cargo +nightly-2018-07-17-x86_64-unknown-linux-gnu install fmt
#rustup default nightly

echo "COMPILING HOLOCHAIN-CMD"
cd /holochain/holochain-cmd
git pull
cargo update
cargo +nightly build --release

cd /holochain/holosqape
git pull
git submodule init
git submodule update

echo "COMPILING HOLOCHAIN RUST"
cd /holochain/holosqape/holochain-rust
git checkout develop
git pull
cargo update
cargo +$TOOLS_NIGHTLY build --release


echo "COMPILING HOLOSQAPE BINDINGS"
cd /holochain/holosqape/bindings
qmake
make

echo "COMPILING HCSHELL"
cd /holochain/holosqape/hcshell
qmake CONFIG+=release
make clean
make
